version: '3.8'
services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./backend:/app
      - sqlite_data:/app/instance
    restart: unless-stopped
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - todo-network

volumes:
  sqlite_data:
  
networks:
  todo-network:
    driver: bridge